services:
  backend:
    image: ghcr.io/simonwep/genesis:v1.4.1
    restart: unless-stopped
    volumes:
      - ./data:/app/.data
    command: start
    env_file:
      - .env

  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8081:80"

  nginx:
    image: nginx:1.26-alpine
    restart: unless-stopped
    ports:
      - "3030:80"
